debug: true

server:
  port: 8089
  servlet:
    context-path: /eventify

spring:
  security:
    user:
      name: admin
      password: admin
  datasource:
    url: jdbc:postgresql://localhost:5432/eventify
    username: postgres
    password: asdasd123
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
    
        