CREATE TABLE users (
	user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nickname VARCHAR(255) NOT NULL,
	first_name VARCHAR(255) NOT NULL,
	last_name VARCHAR(255) NOT NULL,
	pswd VARCHAR(255),
	email VARCHAR(255),
	phone_number VARCHAR(20),
	email_verified BOOLEAN,
	phone_verified BOOLEAN,
	active BOOLEAN
);
