CREATE TABLE courses (
	course_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	title VARCHAR(255),
	description TEXT,
	fk_creator_id INT,
	FOREIGN KEY (fk_creator_id) REFERENCES users(user_id)
);

CREATE TABLE events (
	event_id INT GENERATED BY DEFAULT AS PRIMARY KEY,
	title VARCHAR(255),
	description TEXT,
	event_time TIMESTAMP,
	fk_course_id INT,
	fk_creator_id INT,
	FOREIGN KEY (fk_course_id) REFERENCES courses(course_id),
	FOREIGN KEY (fk_creator_id) REFERENCES users(user_id)
);

CREATE TABLE user_roles (
	fk_user_id INT NOT NULL,
	user_role VARCHAR(12),
	FOREIGN KEY (fk_user_id) REFERENCES users(user_id)
);